export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const LOAD_HIGHSCORE_REQUEST = 'LOAD_HIGHSCORE_REQUEST';
export const LOAD_HIGHSCORE_SUCCESS = 'LOAD_HIGHSCORE_SUCCESS';
export const LOAD_HIGHSCORE_ERROR = 'LOAD_HIGHSCORE_ERROR';

export const LOAD_LEADERBOARD_REQUEST = 'LOAD_LEADERBOARD_REQUEST';
export const LOAD_LEADERBOARD_SUCCESS = 'LOAD_LEADERBOARD_SUCCESS';
export const LOAD_LEADERBOARD_ERROR = 'LOAD_LEADERBOARD_ERROR';